baseURL = "https://lstolcman.github.io"
languageCode = "en-us"
title = "lstolcman blog"
theme = "hugo-theme-yinyang"
enableEmoji = "true"
footnoteReturnLinkContents = "↩"
# enableRobotsTXT = "true"
defaultContentLanguage = 'en'
# [permalinks]
#   posts = "/:year/:month/:title/"

[params]
headTitle = "lstolcman blog"
# postHeaderContent = ""
# postFooterContent = "<br/><br/><p>Subscribe：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"


# [[params.socials]]
# name = "About Me"
# link = "https://joway.io"

[[params.socials]]
name = "Github"
link = "https://github.com/lstolcman"
